# ===========================================
# DevFlow Supabase 자동 설정 스크립트
# ===========================================
# 사용법: .\scripts\setup-supabase.ps1
# ===========================================

param(
    [string]$ProjectName = "devflow",
    [string]$Region = "northeast-asia-northeast1"
)

$ErrorActionPreference = "Stop"
$supabase = "$env:USERPROFILE\scoop\shims\supabase.exe"

Write-Host "===========================================`n" -ForegroundColor Cyan
Write-Host " DevFlow Supabase Setup" -ForegroundColor Cyan
Write-Host "`n===========================================" -ForegroundColor Cyan

# 1. Supabase CLI 확인
if (-not (Test-Path $supabase)) {
    Write-Host "`n[ERROR] Supabase CLI not found!" -ForegroundColor Red
    Write-Host "Install with: scoop install supabase" -ForegroundColor Yellow
    exit 1
}

$version = & $supabase --version
Write-Host "`n[OK] Supabase CLI: $version" -ForegroundColor Green

# 2. Access Token 확인
Write-Host "`n------------------------------------------"
Write-Host " Step 1: Supabase Access Token" -ForegroundColor Yellow
Write-Host "------------------------------------------"

if ($env:SUPABASE_ACCESS_TOKEN) {
    Write-Host "[OK] SUPABASE_ACCESS_TOKEN found in environment" -ForegroundColor Green
} else {
    Write-Host "`nAccess Token not found. Please:"
    Write-Host "1. Go to: https://supabase.com/dashboard/account/tokens"
    Write-Host "2. Click 'Generate new token'"
    Write-Host "3. Copy the token`n"

    $token = Read-Host "Paste your Supabase Access Token"

    if ([string]::IsNullOrEmpty($token)) {
        Write-Host "[ERROR] Token required!" -ForegroundColor Red
        exit 1
    }

    $env:SUPABASE_ACCESS_TOKEN = $token
    Write-Host "[OK] Token set" -ForegroundColor Green
}

# 3. 프로젝트 목록 확인
Write-Host "`n------------------------------------------"
Write-Host " Step 2: Project Selection" -ForegroundColor Yellow
Write-Host "------------------------------------------"

Write-Host "`nFetching your Supabase projects..."
$projects = & $supabase projects list --token $env:SUPABASE_ACCESS_TOKEN 2>&1

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Failed to fetch projects. Check your token." -ForegroundColor Red
    Write-Host $projects -ForegroundColor Red
    exit 1
}

Write-Host "`nYour projects:`n"
Write-Host $projects

# 4. 프로젝트 선택 또는 생성
Write-Host "`n------------------------------------------"
Write-Host " Step 3: Project Link" -ForegroundColor Yellow
Write-Host "------------------------------------------"

$projectRef = Read-Host "`nEnter project ref (ID) to link, or 'new' to create"

if ($projectRef -eq "new") {
    Write-Host "`nCreating new project: $ProjectName"

    # Organization 확인
    $orgs = & $supabase orgs list --token $env:SUPABASE_ACCESS_TOKEN
    Write-Host "`nYour organizations:"
    Write-Host $orgs

    $orgId = Read-Host "Enter organization ID"
    $dbPassword = Read-Host "Enter database password (min 6 chars)" -AsSecureString
    $dbPasswordPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($dbPassword))

    & $supabase projects create $ProjectName `
        --org-id $orgId `
        --region $Region `
        --db-password $dbPasswordPlain `
        --token $env:SUPABASE_ACCESS_TOKEN

    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ERROR] Failed to create project" -ForegroundColor Red
        exit 1
    }

    Write-Host "`n[OK] Project created! Waiting for initialization..." -ForegroundColor Green
    Start-Sleep -Seconds 30

    # 새 프로젝트 목록에서 ref 가져오기
    $projects = & $supabase projects list --token $env:SUPABASE_ACCESS_TOKEN
    Write-Host $projects
    $projectRef = Read-Host "Enter the new project's ref"
}

# 5. 프로젝트 연결
Write-Host "`nLinking to project: $projectRef"
Set-Location "D:\AI\claude01\project_master\frontend"

& $supabase link --project-ref $projectRef --token $env:SUPABASE_ACCESS_TOKEN

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Failed to link project" -ForegroundColor Red
    exit 1
}

Write-Host "[OK] Project linked!" -ForegroundColor Green

# 6. 환경변수 생성
Write-Host "`n------------------------------------------"
Write-Host " Step 4: Environment Variables" -ForegroundColor Yellow
Write-Host "------------------------------------------"

# API Keys 가져오기
$apiUrl = "https://$projectRef.supabase.co"
Write-Host "`nProject URL: $apiUrl"

Write-Host "`nPlease get your anon key from:"
Write-Host "https://supabase.com/dashboard/project/$projectRef/settings/api"
$anonKey = Read-Host "`nPaste your anon (public) key"

# .env.local 생성
$envContent = @"
# DevFlow Supabase Configuration
# Generated by setup-supabase.ps1

NEXT_PUBLIC_SUPABASE_URL=$apiUrl
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anonKey
"@

$envPath = "D:\AI\claude01\project_master\frontend\.env.local"
$envContent | Out-File -FilePath $envPath -Encoding UTF8

Write-Host "`n[OK] Created .env.local" -ForegroundColor Green

# 7. GitHub OAuth 안내
Write-Host "`n------------------------------------------"
Write-Host " Step 5: GitHub OAuth Setup" -ForegroundColor Yellow
Write-Host "------------------------------------------"

Write-Host "`nTo enable GitHub login:`n"
Write-Host "1. Go to: https://supabase.com/dashboard/project/$projectRef/auth/providers"
Write-Host "2. Enable 'GitHub' provider"
Write-Host "3. Create GitHub OAuth App at: https://github.com/settings/developers"
Write-Host "4. Set callback URL to: $apiUrl/auth/v1/callback"
Write-Host "5. Enter Client ID and Secret in Supabase"

# 8. 완료
Write-Host "`n===========================================" -ForegroundColor Green
Write-Host " Setup Complete!" -ForegroundColor Green
Write-Host "===========================================" -ForegroundColor Green
Write-Host "`nNext steps:"
Write-Host "1. Configure GitHub OAuth (see step 5 above)"
Write-Host "2. Start dev server: npm run dev"
Write-Host "3. Test login at: http://localhost:3000"
